# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

### Create an array

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [9]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [14]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [17]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [16]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
np.random.rand(2,4)


array([[0.11565792, 0.31732861, 0.84622312, 0.80511188],
       [0.16315614, 0.6565607 , 0.05278299, 0.50867627]])

In [20]:
np.random.randn(2,4)

array([[-0.66535831, -0.23657513, -1.06227806,  0.02046374],
       [ 2.0826108 , -0.66418843,  0.54544136, -1.37985666]])

In [18]:
np.random.rand(2,5)

array([[0.28933643, 0.62145975, 0.0152351 , 0.72667011, 0.33152295],
       [0.33807016, 0.67341856, 0.10844023, 0.42884949, 0.77832811]])

In [19]:
np.random.randint(0,10,15)

array([9, 5, 5, 2, 0, 6, 4, 3, 6, 5, 3, 3, 5, 7, 8])

In [20]:
np.random.randint(10,100,15)

array([62, 29, 64, 84, 49, 29, 54, 72, 44, 60, 55, 64, 71, 88, 24])

In [21]:
np.random.randint(20,56,100)

array([37, 25, 31, 54, 27, 50, 52, 41, 37, 48, 38, 39, 21, 22, 53, 45, 21,
       49, 26, 29, 34, 52, 31, 38, 21, 26, 41, 32, 48, 36, 51, 49, 36, 37,
       28, 40, 52, 53, 42, 54, 25, 24, 26, 48, 27, 37, 22, 52, 24, 42, 36,
       33, 40, 24, 36, 38, 29, 35, 40, 52, 28, 32, 50, 23, 49, 53, 34, 49,
       21, 35, 22, 35, 24, 43, 51, 55, 51, 51, 33, 45, 32, 32, 23, 22, 54,
       27, 44, 29, 34, 38, 26, 30, 55, 42, 44, 52, 20, 47, 38, 53])

In [25]:
import numpy as np

In [22]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
rand_array=np.random.randint(0,10,5)
rand_array

array([3, 0, 8, 9, 4])

In [24]:
sample_array.min()

2

In [25]:
sample_array.argmin()

0

In [26]:
rand_array.argmin()

1

In [27]:
rand_array.max()

9

In [28]:
rand_array.argmax()

3

In [30]:
sample_array.argmax()

17

In [31]:
sample_array.dtype

dtype('int32')

In [32]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
a=np.random.rand(2,3)
a

array([[0.2455647 , 0.39349287, 0.15365567],
       [0.83313096, 0.34367683, 0.66307429]])

In [38]:
a.T

array([[0.18183096, 0.26625638],
       [0.57404437, 0.10479009],
       [0.89286401, 0.85216754]])

In [35]:
import numpy as np

In [36]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [37]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [38]:
sample_array=sample_array.reshape(9,2)
sample_array

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27]])

In [39]:
sample_array[5]=100
sample_array

array([[ 10,  11],
       [ 12,  13],
       [ 14,  15],
       [ 16,  17],
       [ 18,  19],
       [100, 100],
       [ 22,  23],
       [ 24,  25],
       [ 26,  27]])

In [40]:
sample_array=np.arange(10,100)
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [41]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [42]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [43]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

### Two-Dimensional array

In [44]:
import numpy as np

In [45]:
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [46]:
sample_matrix[2][2]

24

In [47]:
sample_matrix[1][2]

54

In [48]:
sample_matrix[:,2]

array([ 2, 54, 24])

In [49]:
sample_matrix[1,1]

2

In [50]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [51]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [52]:
sample_matrix[2]

array([56, 76, 24,  7])

In [53]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [54]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [55]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [56]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [57]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [58]:
np.max(sample_array)

30

In [59]:
np.min(sample_array)

1

In [60]:
np.argmax(sample_array)

29

In [61]:
np.argmin(sample_array)

0

In [62]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [63]:
np.std(sample_array)

8.65544144839919

In [64]:
np.var(sample_array)


74.91666666666667

In [65]:
np.mean(sample_array)

15.5

In [66]:
array=np.random.randn(3,4) ### normal distribution
array

array([[-0.72204179, -0.39829792, -0.14582656, -1.3277332 ],
       [-0.14671227,  0.66978018,  0.31428195, -0.43711112],
       [-1.74219337,  1.08194053,  0.94048527,  0.70877195]])

In [67]:
np.round(array,decimals=3)

array([[-0.722, -0.398, -0.146, -1.328],
       [-0.147,  0.67 ,  0.314, -0.437],
       [-1.742,  1.082,  0.94 ,  0.709]])

In [68]:
sports=np.array(['golf','cricket','fball','cricket','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')

### Pandas

In [69]:
import pandas as pd

In [70]:
labels=['a','b','c','d']


In [71]:
list=[10,28,3,4]


In [72]:
import numpy as np

In [73]:
array=np.array([1,2,3,4])


In [74]:
dict={'w':10,'x':20,'y':30,'z':40}

In [75]:
pd.Series(list)


0    10
1    28
2     3
3     4
dtype: int64

In [76]:
pd.Series(list,index=labels)

a    10
b    28
c     3
d     4
dtype: int64

In [77]:
pd.Series(labels,list)

10    a
28    b
3     c
4     d
dtype: object

In [78]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

### Pandas dataframe and indexing

In [79]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [80]:
sports1['basketball']

3

In [81]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [82]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [83]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.497739  0.976097  0.181226  0.670803  0.695260
B  0.732578  0.179743  0.364391  0.565151  0.717114
C  0.894341  0.670002  0.337820  0.406198  0.702799
D  0.512398  0.057125  0.525168  0.102510  0.633683
E  0.897072  0.119673  0.568680  0.546420  0.099472
F  0.912716  0.951956  0.869271  0.818505  0.879859
G  0.491329  0.731286  0.778882  0.250032  0.485092
H  0.244225  0.271877  0.310489  0.474039  0.200888

In [84]:
df1['Score3']

A    0.181226
B    0.364391
C    0.337820
D    0.525168
E    0.568680
F    0.869271
G    0.778882
H    0.310489
Name: Score3, dtype: float64

In [85]:
df1[['Score2','Score1','Score5']]

Score2    Score1    Score5
A  0.976097  0.497739  0.695260
B  0.179743  0.732578  0.717114
C  0.670002  0.894341  0.702799
D  0.057125  0.512398  0.633683
E  0.119673  0.897072  0.099472
F  0.951956  0.912716  0.879859
G  0.731286  0.491329  0.485092
H  0.271877  0.244225  0.200888

In [86]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.497739  0.976097  0.181226  0.670803  0.695260  1.473837
B  0.732578  0.179743  0.364391  0.565151  0.717114  0.912322
C  0.894341  0.670002  0.337820  0.406198  0.702799  1.564343
D  0.512398  0.057125  0.525168  0.102510  0.633683  0.569523
E  0.897072  0.119673  0.568680  0.546420  0.099472  1.016745
F  0.912716  0.951956  0.869271  0.818505  0.879859  1.864673
G  0.491329  0.731286  0.778882  0.250032  0.485092  1.222614
H  0.244225  0.271877  0.310489  0.474039  0.200888  0.516101

In [87]:
df1.drop('Score5',axis=1) 

Score1    Score2    Score3    Score4    Score6
A  0.497739  0.976097  0.181226  0.670803  1.473837
B  0.732578  0.179743  0.364391  0.565151  0.912322
C  0.894341  0.670002  0.337820  0.406198  1.564343
D  0.512398  0.057125  0.525168  0.102510  0.569523
E  0.897072  0.119673  0.568680  0.546420  1.016745
F  0.912716  0.951956  0.869271  0.818505  1.864673
G  0.491329  0.731286  0.778882  0.250032  1.222614
H  0.244225  0.271877  0.310489  0.474039  0.516101

In [88]:
df1.drop("E",axis=0)

Score1    Score2    Score3    Score4    Score5    Score6
A  0.497739  0.976097  0.181226  0.670803  0.695260  1.473837
B  0.732578  0.179743  0.364391  0.565151  0.717114  0.912322
C  0.894341  0.670002  0.337820  0.406198  0.702799  1.564343
D  0.512398  0.057125  0.525168  0.102510  0.633683  0.569523
F  0.912716  0.951956  0.869271  0.818505  0.879859  1.864673
G  0.491329  0.731286  0.778882  0.250032  0.485092  1.222614
H  0.244225  0.271877  0.310489  0.474039  0.200888  0.516101

In [89]:
df2={'ID':[101,102,103,107,176],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [90]:
df.drop('ID',axis=1)

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavin      87
4  Lally     123

In [91]:
df.drop(3)

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
4  176  Lally     123

In [92]:
df['Name']

0     John
1    Mercy
2    Akash
3    Kavin
4    Lally
Name: Name, dtype: object

In [93]:
df[['Name','ID']]

Name   ID
0   John  101
1  Mercy  102
2  Akash  103
3  Kavin  107
4  Lally  176